action_id: trunk-upgrade-available
date: 2023-03-30 14:45:27
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: line 1: trunk: command not found\n"
timestamp: 1680187527
full_timestamp:
  nanos: 437685000
  seconds: 1680187527
trunk_version: 1.6.0
