action_id: trunk-share-with-everyone
date: 2023-03-30 13:45:27
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 127
  out: ""
  err: "trunk-share-with-everyone: line 1: trunk: command not found\n"
timestamp: 1680183927
full_timestamp:
  nanos: 450769000
  seconds: 1680183927
trunk_version: 1.6.0
